version: "3.8"
services:
  inventory_service:
    build: ./inventory_service
    ports:
      - "5001:5001"
  user_service:
    build: ./user_service
    ports:
      - "5002:5002"
  report_service:
    build: ./report_service
    ports:
      - "5003:5003"
    depends_on:
      - inventory_service
